package com.hiyichang.infohub.mapper;

import com.hiyichang.infohub.entity.ProcedureStep;
import com.hiyichang.infohub.entity.ProcedureStepExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcedureStepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    long countByExample(ProcedureStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    int deleteByExample(ProcedureStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    int insert(ProcedureStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    int insertSelective(ProcedureStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    List<ProcedureStep> selectByExample(ProcedureStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    ProcedureStep selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProcedureStep record, @Param("example") ProcedureStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    int updateByExample(@Param("record") ProcedureStep record, @Param("example") ProcedureStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    int updateByPrimaryKeySelective(ProcedureStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    int updateByPrimaryKey(ProcedureStep record);
}