package com.hiyichang.infohub.entity;

import java.io.Serializable;
import java.util.Date;

public class Customer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_title
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String customerTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_lastname
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String customerLastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_firstname
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String customerFirstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone_number
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.birthday
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.gender
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.delete_flag
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_title
     *
     * @return the value of customer.customer_title
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getCustomerTitle() {
        return customerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_title
     *
     * @param customerTitle the value for customer.customer_title
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setCustomerTitle(String customerTitle) {
        this.customerTitle = customerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_lastname
     *
     * @return the value of customer.customer_lastname
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getCustomerLastname() {
        return customerLastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_lastname
     *
     * @param customerLastname the value for customer.customer_lastname
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setCustomerLastname(String customerLastname) {
        this.customerLastname = customerLastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_firstname
     *
     * @return the value of customer.customer_firstname
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getCustomerFirstname() {
        return customerFirstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_firstname
     *
     * @param customerFirstname the value for customer.customer_firstname
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setCustomerFirstname(String customerFirstname) {
        this.customerFirstname = customerFirstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone_number
     *
     * @return the value of customer.phone_number
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone_number
     *
     * @param phoneNumber the value for customer.phone_number
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.birthday
     *
     * @return the value of customer.birthday
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.birthday
     *
     * @param birthday the value for customer.birthday
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.gender
     *
     * @return the value of customer.gender
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.gender
     *
     * @param gender the value for customer.gender
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.delete_flag
     *
     * @return the value of customer.delete_flag
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.delete_flag
     *
     * @param deleteFlag the value for customer.delete_flag
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}