package com.hiyichang.infohub.entity;

import java.io.Serializable;
import java.util.Date;

public class Employee implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.account_id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.birthday
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.phone_number
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.gender
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.login_passwd
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String loginPasswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.account_id
     *
     * @return the value of employee.account_id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.account_id
     *
     * @param accountId the value for employee.account_id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.birthday
     *
     * @return the value of employee.birthday
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.birthday
     *
     * @param birthday the value for employee.birthday
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.phone_number
     *
     * @return the value of employee.phone_number
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.phone_number
     *
     * @param phoneNumber the value for employee.phone_number
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.gender
     *
     * @return the value of employee.gender
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.gender
     *
     * @param gender the value for employee.gender
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.login_passwd
     *
     * @return the value of employee.login_passwd
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getLoginPasswd() {
        return loginPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.login_passwd
     *
     * @param loginPasswd the value for employee.login_passwd
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setLoginPasswd(String loginPasswd) {
        this.loginPasswd = loginPasswd;
    }
}