package com.hiyichang.infohub.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProcedureStepExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public ProcedureStepExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIsNull() {
            addCriterion("order is null");
            return (Criteria) this;
        }

        public Criteria andOrderIsNotNull() {
            addCriterion("order is not null");
            return (Criteria) this;
        }

        public Criteria andOrderEqualTo(Long value) {
            addCriterion("order_id =", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotEqualTo(Integer value) {
            addCriterion("order <>", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderGreaterThan(Integer value) {
            addCriterion("order >", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("order >=", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderLessThan(Integer value) {
            addCriterion("order <", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderLessThanOrEqualTo(Integer value) {
            addCriterion("order <=", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderIn(List<Integer> values) {
            addCriterion("order in", values, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotIn(List<Integer> values) {
            addCriterion("order not in", values, "order");
            return (Criteria) this;
        }

        public Criteria andOrderBetween(Integer value1, Integer value2) {
            addCriterion("order between", value1, value2, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("order not between", value1, value2, "order");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andFinishDatetimeIsNull() {
            addCriterion("finish_datetime is null");
            return (Criteria) this;
        }

        public Criteria andFinishDatetimeIsNotNull() {
            addCriterion("finish_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andFinishDatetimeEqualTo(Date value) {
            addCriterion("finish_datetime =", value, "finishDatetime");
            return (Criteria) this;
        }

        public Criteria andFinishDatetimeNotEqualTo(Date value) {
            addCriterion("finish_datetime <>", value, "finishDatetime");
            return (Criteria) this;
        }

        public Criteria andFinishDatetimeGreaterThan(Date value) {
            addCriterion("finish_datetime >", value, "finishDatetime");
            return (Criteria) this;
        }

        public Criteria andFinishDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("finish_datetime >=", value, "finishDatetime");
            return (Criteria) this;
        }

        public Criteria andFinishDatetimeLessThan(Date value) {
            addCriterion("finish_datetime <", value, "finishDatetime");
            return (Criteria) this;
        }

        public Criteria andFinishDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("finish_datetime <=", value, "finishDatetime");
            return (Criteria) this;
        }

        public Criteria andFinishDatetimeIn(List<Date> values) {
            addCriterion("finish_datetime in", values, "finishDatetime");
            return (Criteria) this;
        }

        public Criteria andFinishDatetimeNotIn(List<Date> values) {
            addCriterion("finish_datetime not in", values, "finishDatetime");
            return (Criteria) this;
        }

        public Criteria andFinishDatetimeBetween(Date value1, Date value2) {
            addCriterion("finish_datetime between", value1, value2, "finishDatetime");
            return (Criteria) this;
        }

        public Criteria andFinishDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("finish_datetime not between", value1, value2, "finishDatetime");
            return (Criteria) this;
        }

        public Criteria andExpectDeliverTimeIsNull() {
            addCriterion("expect_deliver_time is null");
            return (Criteria) this;
        }

        public Criteria andExpectDeliverTimeIsNotNull() {
            addCriterion("expect_deliver_time is not null");
            return (Criteria) this;
        }

        public Criteria andExpectDeliverTimeEqualTo(Date value) {
            addCriterionForJDBCDate("expect_deliver_time =", value, "expectDeliverTime");
            return (Criteria) this;
        }

        public Criteria andExpectDeliverTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("expect_deliver_time <>", value, "expectDeliverTime");
            return (Criteria) this;
        }

        public Criteria andExpectDeliverTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("expect_deliver_time >", value, "expectDeliverTime");
            return (Criteria) this;
        }

        public Criteria andExpectDeliverTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("expect_deliver_time >=", value, "expectDeliverTime");
            return (Criteria) this;
        }

        public Criteria andExpectDeliverTimeLessThan(Date value) {
            addCriterionForJDBCDate("expect_deliver_time <", value, "expectDeliverTime");
            return (Criteria) this;
        }

        public Criteria andExpectDeliverTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("expect_deliver_time <=", value, "expectDeliverTime");
            return (Criteria) this;
        }

        public Criteria andExpectDeliverTimeIn(List<Date> values) {
            addCriterionForJDBCDate("expect_deliver_time in", values, "expectDeliverTime");
            return (Criteria) this;
        }

        public Criteria andExpectDeliverTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("expect_deliver_time not in", values, "expectDeliverTime");
            return (Criteria) this;
        }

        public Criteria andExpectDeliverTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("expect_deliver_time between", value1, value2, "expectDeliverTime");
            return (Criteria) this;
        }

        public Criteria andExpectDeliverTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("expect_deliver_time not between", value1, value2, "expectDeliverTime");
            return (Criteria) this;
        }

        public Criteria andOperatorEmployeeIdIsNull() {
            addCriterion("operator_employee_id is null");
            return (Criteria) this;
        }

        public Criteria andOperatorEmployeeIdIsNotNull() {
            addCriterion("operator_employee_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEmployeeIdEqualTo(Long value) {
            addCriterion("operator_employee_id =", value, "operatorEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOperatorEmployeeIdNotEqualTo(Long value) {
            addCriterion("operator_employee_id <>", value, "operatorEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOperatorEmployeeIdGreaterThan(Long value) {
            addCriterion("operator_employee_id >", value, "operatorEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOperatorEmployeeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("operator_employee_id >=", value, "operatorEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOperatorEmployeeIdLessThan(Long value) {
            addCriterion("operator_employee_id <", value, "operatorEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOperatorEmployeeIdLessThanOrEqualTo(Long value) {
            addCriterion("operator_employee_id <=", value, "operatorEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOperatorEmployeeIdIn(List<Long> values) {
            addCriterion("operator_employee_id in", values, "operatorEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOperatorEmployeeIdNotIn(List<Long> values) {
            addCriterion("operator_employee_id not in", values, "operatorEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOperatorEmployeeIdBetween(Long value1, Long value2) {
            addCriterion("operator_employee_id between", value1, value2, "operatorEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOperatorEmployeeIdNotBetween(Long value1, Long value2) {
            addCriterion("operator_employee_id not between", value1, value2, "operatorEmployeeId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table procedure_step
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 27 02:48:51 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}