package com.hiyichang.infohub.entity;

import java.io.Serializable;
import java.util.Date;

public class ProcedureStep implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procedure_step.id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procedure_step.order
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procedure_step.name
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procedure_step.remark
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procedure_step.finish_datetime
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private Date finishDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procedure_step.expect_deliver_time
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private Date expectDeliverTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procedure_step.operator_employee_id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private Long operatorEmployeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procedure_step.status
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table procedure_step
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procedure_step.id
     *
     * @return the value of procedure_step.id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procedure_step.id
     *
     * @param id the value for procedure_step.id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procedure_step.order
     *
     * @return the value of procedure_step.order
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procedure_step.order
     *
     * @param orderId the value for procedure_step.order
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procedure_step.name
     *
     * @return the value of procedure_step.name
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procedure_step.name
     *
     * @param name the value for procedure_step.name
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procedure_step.remark
     *
     * @return the value of procedure_step.remark
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procedure_step.remark
     *
     * @param remark the value for procedure_step.remark
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procedure_step.finish_datetime
     *
     * @return the value of procedure_step.finish_datetime
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public Date getFinishDatetime() {
        return finishDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procedure_step.finish_datetime
     *
     * @param finishDatetime the value for procedure_step.finish_datetime
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setFinishDatetime(Date finishDatetime) {
        this.finishDatetime = finishDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procedure_step.expect_deliver_time
     *
     * @return the value of procedure_step.expect_deliver_time
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public Date getExpectDeliverTime() {
        return expectDeliverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procedure_step.expect_deliver_time
     *
     * @param expectDeliverTime the value for procedure_step.expect_deliver_time
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setExpectDeliverTime(Date expectDeliverTime) {
        this.expectDeliverTime = expectDeliverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procedure_step.operator_employee_id
     *
     * @return the value of procedure_step.operator_employee_id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public Long getOperatorEmployeeId() {
        return operatorEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procedure_step.operator_employee_id
     *
     * @param operatorEmployeeId the value for procedure_step.operator_employee_id
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setOperatorEmployeeId(Long operatorEmployeeId) {
        this.operatorEmployeeId = operatorEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procedure_step.status
     *
     * @return the value of procedure_step.status
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procedure_step.status
     *
     * @param status the value for procedure_step.status
     *
     * @mbg.generated Sat Jun 27 02:48:51 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }
}